In [10]:
# IF ELSE STATEMENT EXAMPLE

a = 25
b = 50

if a > b:
    print('a is greater than b')
else:
    print('a is less than b')

a is less than b


In [4]:
# NUMPY - example of creating a numpy array and using for and .flat to create a new flattened version of this array

import numpy as np

array = np.array([[2, 4, 6,], 
                 [8, 10, 12], 
                 [14,16,18]
                 ])  
                 
print(array)



for x in array.flat:
    print(x)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
2
4
6
8
10
12
14
16
18


In [6]:
# example of linking two arrays with numpy

a = np.array([[2, 4, 6,],
              [8, 10, 12],
              [14,16,18]
              ])  


b = np.array([[1, 3, 5,],
              [7, 9, 11],
              [13,15,17]
              ])  
                 
c = np.concatenate((a,b))

print(c)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [14]:
# WEB SCRAPING - found the following website which I used
# https://howpcrules.com/sample-page-for-web-scraping/

from bs4 import BeautifulSoup
import requests
import pandas as pd
    
webscrape = requests.get("http://howpcrules.com/sample-page-for-web-scraping/").text

In [15]:
# store the webscrape / HTML content we have sourced above into BeautifulSoup library, lxml is the parser we will use
# create variable scrape

scrape = BeautifulSoup(webscrape, 'lxml')

In [16]:
scrape

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="A developer's guide on code and beyond" name="description"/>
<!-- Mobile Specific Meta -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
<title>Sample Page for Web Scraping – How PC Rules my Life</title>
<meta content="max-image-preview:large" name="robots"/>
<link href="//fonts.googleapis.com" rel="dns-prefetch"/>
<link href="//s.w.org" rel="dns-prefetch"/>
<link href="https://howpcrules.com/feed/" rel="alternate" title="How PC Rules my Life » Feed" type="application/rss+xml"/>
<link href="https://howpcrules.com/comments/feed/" rel="alternate" title="How PC Rules my Life » Comments Feed" type="application/rss+xml"/>
<script type="text/javascript">
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:

In [22]:
scrape.find(class_="post-title")

<h1 class="post-title">Sample Page for Web Scraping</h1>

In [23]:
scrape.find(class_="t_capt")

<caption class="t_capt">Basic Information</caption>